#ifndef _BS_BSERROR_H_
#define _BS_BSERROR_H_

#define BS_NOERROR			0
#define BS_FAILED			1


//////////////////common//////////////

#define BS_ERROR_UNKNOWN			2
#define BS_ERROR_INVALIDPAGEPOOL	3

#define BS_ERROR_AUTHFAILURE		5
#define BS_ERROR_NAMELEN			6
#define BS_ERROR_GETPAGE			10
#define BS_ERROR_ADDDATATOPAGE		11
#define BS_ERROR_INSERTBPTREE		12
#define BS_ERROR_PAGEHEAD			13
#define BS_ERROR_CREATEOBJECT		14
#define BS_ERROR_GETFREEPAGE		15
#define BS_ERROR_DATAF0RMAT			16
#define BS_ERROR_BUFFERTOOSMALL		17
#define BS_ERROR_COPYDATAFROMPAGE	18
#define BS_ERROR_CHECKSUM			19
#define BS_ERROR_OPENTREE			20
#define BS_ERROR_DELETEBPTREE		21
#define BS_ERROR_ALLOCMEMORY		22
#define BS_ERROR_TIMEOUT			23
#define BS_ERROR_INDEXTREE			24
#define BS_ERROR_INDEXTREETYPE		25
#define BS_ERROR_NONSUPPORT			26
#define BS_ERROR_EMPTYBUFFER		27
#define BS_ERROR_PARAMETER			28
#define BS_ERROR_CLEARPAGEDATA		29
#define BS_ERROR_DESTORYBPTREE		30
#define BS_ERROR_PUSHPAGELIST		31
#define BS_ERROR_POPPAGELIST		32
#define BS_ERROR_PAGETOOSMALL		33
#define BS_ERROR_OPENBPTREE			34
#define BS_ERROR_BPTREEFIND			35
#define BS_ERROR_BPTREEINSERT		36
#define BS_ERROR_BPTREEDELETE		37
#define BS_ERROR_BPTREEDESTORY		38
#define BS_ERROR_BPTREEEDIT			39
#define BS_ERROR_BPTREENOFIND		40
#define BS_ERROR_BPTREEVISIT		41
#define BS_ERROR_BPTREEISEMPTY		42
#define BS_ERROR_OVERWRITETOPAGE	43

/////////////////////IT////////////////
#define BS_IT_ITEMEXISTALLREADY		45

///////////////////IRST/////////////////
#define BS_IRST_PARSEKEYERROR		50
#define BS_IRST_FINEDERROR			51

////////////////////////////////////////////

#define BS_ERROR_STRLISTTOBUFFER	55
#define BS_ERROR_BUFFERTOSTRLIST	56
#define BS_ERROR_OPENTRANSACTION	57
#define BS_ERROR_NOOPENTRANSACTION	58
#define BS_ERROR_COMMITTRANSACTION	59
#define BS_ERROR_ROLLBACKTRANSACTION	60
#define BS_ERROR_TRANSACTIONALREADYBEGIN	61
#define BS_ERROR_DATAPROTOCOL		62
#define BS_ERROR_CONVERTDATA		63


/////////////////bslist/////////////////

#define BS_LIST_EMPTY				70
#define BS_LIST_INVALIDHEADPID  	71
#define BS_LIST_NOMOREITEM			72
#define BS_LIST_BADITEMPAGEPOS		73
#define BS_LIST_ITEMCOUNTERROR		74
#define BS_LIST_PAGEDATATYPEERROR	75			



/////////////////mq///////////////////

#define BS_MQ_EXISTALLREADY			120
#define BS_MQ_NOEXIST				121
#define BS_MQ_NOFINDPFHFLAG			122
#define BS_MQ_MQHEADERROR			123
#define BS_MQ_NAMEUNMATCHED			124
#define BS_MQ_GETPOSTIONHEADERROR	125
#define BS_MQ_MQNOINITIALIZATION	126
#define BS_MQ_OPENINDEXTREE			127
#define BS_MQ_INVALIDLEVEL			128
#define BS_MQ_LOADLASTRECORDFAILED	129
#define BS_MQ_ADDDATATOPAGEFAILED	BS_ERROR_ADDDATATOPAGE
#define BS_MQ_EMPTY					131
#define BS_MQ_RELOADMQ				132
#define BS_MQ_RELEASEMQHEAD			134
#define BS_MQ_VISITMQNAMETREE		135
#define BS_MQ_NOFINDMQ				136
#define BS_MQ_ISNOTINDEXMQ			137
#define BS_MQ_NOANYMQ				138

///////////////treedb/////////////////
#define BS_TRDB_NOAUTHORITY_CREATEDBFILE	157
#define BS_TRDB_DBFILEALREADYEXIST		158
#define BS_TRDB_INITDBFILE				159
#define BS_TRDB_NOINITIALIZATION		160
#define BS_TRDB_MAINKEYISEMPTY			161
#define BS_TRDB_MAINKEYALREADYEXIST		162
#define BS_TRDB_READMAINKEYTREEROOTFAILED	163
#define BS_TRDB_WRITEMAINKEYTREEROOTFAILED	164
#define BS_TRDB_NOFINDPFHFLAG			165
#define BS_TRDB_TRDBHEADERROR			166
#define BS_TRDB_NODENAMELENERROR		167
#define BS_TRDB_NODENAMEMISMATCH		168
#define BS_TRDB_MAINKEYNOEXIST			169
#define BS_TRDB_NOAUTHORITY_CREATESYSTEMKEY		170
#define BS_TRDB_FINDMAINKEYEXCEPTION	171
#define BS_TRDB_NOFINDMAINKEY			172
#define BS_TRDB_NOFINDNODEPAGEFLAG		173
#define BS_TRDB_OPENINDEXTREEFAILED		174
#define BS_TRDB_SUBKEYALREADYEXIST		175
#define BS_TRDB_NOFINDITEM				176
#define BS_TRDB_UNKNOWNSUBKEYMODE		177
#define BS_TRDB_INSERTINDEXTREEFAILED	BS_ERROR_INSERTBPTREE
#define BS_TRDB_NAMEISEMPTY				179
#define BS_TRDB_PROPERTYALREADYEXIST	180
#define BS_TRDB_PROPERTYNAMEALREADYEXIST	181
#define BS_TRDB_DELETEINDEXTREEFAILED	182
#define BS_TRDB_INDEXTREEROOTISNULL		183
#define BS_TRDB_DELETEPROPERTY			184
#define BS_TRDB_VISITNODEINDEXTREE		185
#define BS_TRDB_FLAGUNKNOW	    		186
#define BS_TRDB_PARSEDOTPATHFAILED		187
#define BS_TRDB_PARSENODEPATHFAILED		188
#define BS_TRDB_NOFINDTREEDBFILE		189
#define BS_TRDB_CANNOTRENAMEMAINKEY		190
#define BS_TRDB_CANNOTDELETEMAINKEY		191



///////////////tabledb////////////////////////////////////////

#define BS_TBDB_NOINITIALIZATION		260
#define BS_TBDB_USERALREADYEXIST		261
#define BS_TBDB_INSERTINDEXTREEFAILED	BS_ERROR_INSERTBPTREE
#define BS_TBDB_DBALREADYEXIST			263
#define BS_TBDB_NOFINDDB				264
#define BS_TBDB_TABLEALREADYEXIST		265
#define BS_TBDB_CREATEFIELDBUFFER		266
#define BS_TBDB_UNKNOWNDATATYPE			267
#define BS_TBDB_PRIMARYKEYWITHOUTUNIQUE		268
#define BS_TBDB_PRIMARYREPEATASSIGN		269
#define BS_TBDB_READFIELDHEAD			270
#define BS_TBDB_FIELDFLAGERROR			271
#define BS_TBDB_FIELDPOSERROR			272
#define BS_TBDB_READFIELDINFOERROR		273
#define BS_TBDB_FIELDTYPEERROR			274
#define BS_TBDB_UNKNOWNFIELDTYPE		275
#define BS_TBDB_DATALENGTHERROR			276
#define BS_TBDB_WRITEFIELDINFOERROR		277
#define BS_TBDB_CREATEINDEXTYPEERROR	278
#define BS_TBDB_DYNPAGEERROR			279
#define BS_TBDB_NOFINDTABLE				280
#define BS_TBDB_GETTABLELOCKFAILED		281
#define BS_TBDB_RECORDCBLENERROR		282
#define BS_TBDB_RECORDPRIMARYKEYERROR	283
#define BS_TBDB_SEEKPAGEPOSERROR		284
#define BS_TBDB_INDEXERROR				285
#define BS_TBDB_TABLECBLENERROR			286
#define BS_TBDB_TABLEWASDELETED			287
#define BS_TBDB_NOFINDRECORD			288
#define BS_TBDB_CONDITIONERROR			289
#define BS_TBDB_UNFIXEDFIELD			290
#define BS_TBDB_RECORDSIZEERROR			291
#define BS_TBDB_NOFINDFIELD				292
#define BS_TBDB_FIELDCOUNTERROR			293
#define BS_TBDB_STRLISTTOBUFFERERROR	BS_ERROR_STRLISTTOBUFFER
#define BS_TBDB_BUFFERTOSTRLISTERROR	BS_ERROR_BUFFERTOSTRLIST
#define BS_TBDB_NOFINDDYN				296
#define BS_TBDB_NOTALERTINFO			297
#define BS_TBDB_FIXEDRDSIZEERROR		298
#define BS_TBDB_NOSUPPORTBINARYPRIMARYKEY	299
#define BS_TBDB_NOSUPPORTBINARYINDEX	300
#define BS_TBDB_FIELDSIZEERROR			301
#define BS_TBDB_NOSUPPORTBINCONDITION	302
#define BS_TBDB_DATABUFFERERROR			303
#define BS_TBDB_CONTINUE				304
#define BS_TBDB_END						305

///////////////////////////////////////////////////////////////////////////

#define BSAPI_ERROR_PARAMETER				1000
#define BSAPI_ERROR_CREATEOBJECT			1001
#define BSAPI_ERROR_CONNECTSERVER			1002
#define BSAPI_ERROR_ALLOCMEMORY				1003
#define BSAPI_ERROR_NOSUPPORT_NETIOTYPE		1004
#define BSAPI_ERROR_SENDDATA				1005
#define BSAPI_ERROR_RECVDATA				1006
#define BSAPI_ERROR_DATACHECK				1007
#define BSAPI_ERROR_INVALIDHANDLE			1008
#define BSAPI_ERROR_REOPENMQ				1009
#define BSAPI_ERROR_SERIALDATA				1010
#define BSAPI_ERROR_UNSERIALDATA			1011
#define BSAPI_ERROR_DATAFORMAT				1012
#define BSAPI_ERROR_CREATESTRINGLIST		1013
#define BSAPI_ERROR_CREATESTRINGLISTBUFFER	1014
#define BSAPI_ERROR_NOSUPPORT_DATATYPE		1015
#define BSAPI_ERROR_FIELDDATA				1016
#define BSAPI_ERROR_RECORDDATA				1017
#define BSAPI_ERROR_PARSERECORDDATA			1018
#define BSAPI_ERROR_ERRORHANDLE				1019
#define BSAPI_ERROR_RECORDSET				1020
#define BSAPI_CURSOR_END					1021
#define BSAPI_CURSOR_BEGIN					1022
#define BSAPI_ERROR_SESSIONCLOSED			1023
#define BSAPI_ERROR_TRANHANDLEABORTED		1024
































#endif